Fix unauthorized_client error on Login for Visual Studio F5 experience
dotnet/eShopOnContainers pull request #1318
Opened 2020-05-10 09:25 UTC by fcastells

By setting the correct DockerServiceUrl in docker-compose.dcproj

2020-05-12 13:08 UTC, mvelosop requested changes
Hi @fcastells, thanks for the PR 😊

Just a minor tweak and it'd be good to go!

2020-05-12 13:08 UTC, mvelosop commented on src/docker-compose.dcproj
> +    <DockerServiceUrl>http://docker.for.win.localhost:5100</DockerServiceUrl>
The address should be `host.docker.internal`, as docker.for.win.localhost is now deprecated.
```suggestion
    <DockerServiceUrl>http://host.docker.internal:5100</DockerServiceUrl>
```

2020-08-31 10:37 UTC, sughosneo commented
> By setting the correct DockerServiceUrl in docker-compose.dcproj

Hello @fcastells , thank you for submitting this PR. 
As @mvelosop, suggested in his review, Could you please make respective changes and update the PR ?

2020-08-31 11:24 UTC, fcastells commented
@sughosneo @mvelosop sorry for never following up on this. I forgot the exact details, but I think the requested change is not that simple, because that URL was also somewhere else (In a test database, I believe) and I wanted to make sure of it. But I never did... I'll look at it and submit it to review again.

2021-03-02 09:36 UTC, sughosneo commented
Hi @fcastells , the required change has already been taken care part of `.NET 5` update. So I am closing this PR as of now. 
You can take the latest from the `dev` branch and test out the changes at your end. 

Thank you.

2021-03-02 09:36 UTC, closed without merging