Remove Autofac from the EventBusRabbitMQ project
dotnet/eShopOnContainers pull request #1678
Opened 2021-05-24 11:47 UTC by sayganov

This PR includes the following changes:
- Autofac removed from the EventBusRabbitMQ project
- Refactored the EventBusRabbitMQ class

2021-05-24 11:48 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1678) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1678) before we can accept your contribution.<br/><br/>:x: sayganov [sign now](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=1678)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-architecture/eShopOnContainers?pullRequest=1678) it.</sub>

2021-05-27 05:26 UTC, sughosneo commented
Hi @sayganov , thank you for submitting this PR. Will review and update.

2021-09-30 08:22 UTC, Marusyk requested changes
Thanks for your PR.

Removing Autofac is great 👍
However, there are a lot of changes in "code style".

Usually, PRs have to deal with a single specific issue/topic that the PR is improving or adding.
Here's a good blog post of what I mean, written by Miguel de Icaza, from the Xamarin team and a very well recognized folk in the OSS world:

Open Source Contribution Etiquette
http://tirania.org/blog/archive/2010/Dec-31.html

2021-09-30 08:22 UTC, Marusyk commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
> +                        true,
I would not remove parameters name because it is not clear what `true` means in the current context

2021-09-30 08:22 UTC, Marusyk commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
> +                    properties.DeliveryMode = 2;
The comment // persistent was useful. Now it is magic number

2021-09-30 08:22 UTC, Marusyk commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
> +                .WaitAndRetry(_retryCount, retryAttempt => TimeSpan.FromSeconds(Math.Pow(2, retryAttempt)),
IMHO: the previous code formatting was better

2021-09-30 08:22 UTC, Marusyk commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
> +            _logger.LogTrace("Creating RabbitMQ channel to publish event: {EventId} ({EventName})", @event.Id,
Does it make sense to change it?

2021-09-30 08:22 UTC, Marusyk commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
> +        public void SubscribeDynamic<TH>(string eventName) where TH : IDynamicIntegrationEventHandler
Please pay attention to the general coding style

2021-09-30 08:22 UTC, Marusyk commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/EventBusRabbitMQ.cs
> +            channel.QueueDeclare(_queueName,
If you don't use parameter names then it can be all in one line

2022-06-27 12:03 UTC, closed without merging

2022-06-27 12:10 UTC, sayganov commented
@Marusyk, thank you for reviewing and recommending the blog post.
It's been a while and it's better to close the PR and create a new one that meets all the requirements later :)