Updates all the services to .NET 6.0
dotnet/eShopOnContainers pull request #1770
Opened 2021-10-13 06:53 UTC by sughosneo

2021-10-19 15:49 UTC, IEvangelist requested changes
Overall these changes are awesome, there are some areas that I'd like to see addressed and updated before this is merged. One of the biggest concerns was the namespace changes, while I understand that we're moving to file-scoped namespaces - some places the namespace was changed making it three segments longer than necessary. Why was that changed?

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Controllers/HomeController.cs
> +    [HttpGet()]
```suggestion
    [HttpGet]
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
> +﻿namespace Microsoft.eShopOnContainers.Mobile.Shopping.HttpAggregator.Filters
I see the the implicit using declarations helped out here, but why the inconsistency with the file-scoped namespace, see comment below.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
>      namespace Basket.API.Infrastructure.Filters
Why is this not file-scoped?

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Models/BasketData.cs
> +    public List<BasketDataItem> Items { get; set; } = new List<BasketDataItem>();
```suggestion
    public List<BasketDataItem> Items { get; set; } = new();
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Models/OrderData.cs
> +    public List<OrderItemData> OrderItems { get; } = new List<OrderItemData>();
```suggestion
    public List<OrderItemData> OrderItems { get; } = new();
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Services/IBasketService.cs
> +    Task<BasketData> GetById(string id);
I'm not a fan of the inconsistency here. I would ideally like to see APIs that are consistently suffixed with "Async" for all task-like returning methods. Are we able to change this to:

```suggestion
    Task<BasketData> GetByIdAsync(string id);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/BasketController.cs
> +        var basket = await _basket.GetById(data.BuyerId) ?? new BasketData(data.BuyerId);
If the previous API change is made that I requested, this would need to change too.

```suggestion
        var basket = await _basket.GetByIdAsync(data.BuyerId) ?? new BasketData(data.BuyerId);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/BasketController.cs
> +        var currentBasket = await _basket.GetById(data.BasketId);
```suggestion
        var currentBasket = await _basket.GetByIdAsync(data.BasketId);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/BasketController.cs
> +        if (!data.Updates.Any())
Is it possible for `data` or `data.Updates` to be `null`, if so we should guard against that here?

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/HomeController.cs
> +    [HttpGet()]
```suggestion
    [HttpGet]
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/OrderController.cs
> +    public OrderController(IBasketService basketService, IOrderingService orderingService)
```suggestion

    public OrderController(IBasketService basketService, IOrderingService orderingService)
```

Need a space between `.ctor` and field declarations.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/OrderController.cs
> +        if (string.IsNullOrEmpty(basketId))
Is a string value of `" "` valid? We're only checking `null` or `""`, but not whitespace. See [`string.IsNullOrWhitespace`](https://docs.microsoft.com/en-us/dotnet/api/system.string.isnullorwhitespace?view=net-6.0). try to use this instead of `string.IsNullOrEmpty` in most cases.
```suggestion
        if (string.IsNullOrWhitespace(basketId))
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/OrderController.cs
> +        var basket = await _basketService.GetById(basketId);
```suggestion
        var basket = await _basketService.GetByIdAsync(basketId);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
> +                    [ oAuthScheme ] = new [] { "Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator" }
```suggestion
                    [ oAuthScheme ] = new[] { "Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator" }
```

nit

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
> +﻿namespace Microsoft.eShopOnContainers.Web.Shopping.HttpAggregator.Filters
This is very confusing, why do we have nested `namespace` declarations? What's the reasoning for this, to me it's usually a code smell.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/GrpcExceptionInterceptor.cs
> +            var response = await t;
```suggestion
    private async Task<TResponse> HandleResponse<TResponse>(Task<TResponse> task)
    {
        try
        {
            var response = await task;
```

Nit: let's spell this out.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/HttpClientAuthorizationDelegatingHandler.cs
> +        if (!string.IsNullOrEmpty(authorizationHeader))
```suggestion
        if (!string.IsNullOrWhitespace(authorizationHeader))
```

The `" "` value would not be a valid auth header.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/HttpClientAuthorizationDelegatingHandler.cs
> +            request.Headers.Add("Authorization", new List<string>() { authorizationHeader });
Why not use the [`.Authorization` property instead](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.headers.httprequestheaders.authorization?view=net-6.0#System_Net_Http_Headers_HttpRequestHeaders_Authorization)?

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/HttpClientAuthorizationDelegatingHandler.cs
> +        var token = await GetToken();
```suggestion
        var token = await GetTokenAsync();
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/HttpClientAuthorizationDelegatingHandler.cs
>      }
```suggestion
    Task<string> GetTokenAsync()
    {
        const string ACCESS_TOKEN = "access_token";

        return _httpContextAccessor.HttpContext
            .GetTokenAsync(ACCESS_TOKEN);
    }
```

It's awaited where it is consumed, we can avoid an extra state-machine step by just returning the `Task` here that represents the asynchronous operation - as the result is not used here.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/HttpClientAuthorizationDelegatingHandler.cs
> +            request.Headers.Authorization = new AuthenticationHeaderValue("Bearer", token);
See question on line 20, now we're overriding it? This is a bit confusing - should probably comment why this is done this way. Is it conditional based on config vs explicit HTTP call to retrieve a token, but why?

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Models/BasketData.cs
> +    public List<BasketDataItem> Items { get; set; } = new List<BasketDataItem>();
```suggestion
    public List<BasketDataItem> Items { get; set; } = new();
```

Please try to use target-type new expressions when defining object and collection initializers where the type is obvious.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Models/OrderData.cs
> +    public List<OrderItemData> OrderItems { get; } = new List<OrderItemData>();
```suggestion
    public List<OrderItemData> OrderItems { get; } = new();
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Models/UpdateBasketItemData.cs
>      }
```suggestion
```

The parameterless `.ctor` is implicit, and the `NewQty` assignment is redundant. We can delete all of this.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Program.cs
> +﻿BuildWebHost(args).Run();
```suggestion
await ﻿BuildWebHost(args).RunAsync();
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Program.cs
> +﻿BuildWebHost(args).Run();
```suggestion
await ﻿BuildWebHost(args).RunAsync();
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Services/IBasketService.cs
> +    Task<BasketData> GetById(string id);
```suggestion
    Task<BasketData> GetByIdAsync(string id);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Services/OrderApiClient.cs
> +        var url = _urls.Orders + UrlsConfig.OrdersOperations.GetOrderDraft();
```suggestion
        var url = $"{_urls.Orders}{UrlsConfig.OrdersOperations.GetOrderDraft()}";
```

Interpolated strings over concatenation.

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Services/OrderApiClient.cs
> +        });
I wonder if it wouldn't be easier to just use the [HTTP extensions library, and `PostAsJsonAsync`](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.json.httpclientjsonextensions.postasjsonasync?view=net-6.0)?

2021-10-19 15:49 UTC, IEvangelist commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Startup.cs
> +                            { "webshoppingagg", "Shopping Aggregator for Web Clients" }
```suggestion
                            ["webshoppingagg"] = "Shopping Aggregator for Web Clients" 
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBus/InMemoryEventBusSubscriptionsManager.cs
> +    public bool IsEmpty => !_handlers.Keys.Any();
```suggestion
    public bool IsEmpty => _handlers is { Count: 0 };
```

Use pattern matching, and avoid negation logic as it requires a bit more cognitive load to quickly read.

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBus/InMemoryEventBusSubscriptionsManager.cs
>          }
It might be better to use a `HashSet<Type>` instead of a `List<Type>`, it would make this logic cleaner.

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBus/SubscriptionInfo.cs
>          }
```suggestion
        public static SubscriptionInfo Dynamic(Type handlerType) =>
            new SubscriptionInfo(true, handlerType);

        public static SubscriptionInfo Typed(Type handlerType) =>
            new SubscriptionInfo(false, handlerType);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusRabbitMQ/DefaultRabbitMQPersistentConnection.cs
> +        }
```suggestion
        {
            _connection.ConnectionShutdown -= OnConnectionShutdown;
            _connection.CallbackException -= OnCallbackException;
            _connection.ConnectionBlocked -= OnConnectionBlocked;
            _connection.Dispose();
        }
```

Unwire event handlers when performing clean up.

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
> +                }).GetAwaiter().GetResult();
🙈 I'm going to pretend that I didn't see this... but why are we doing synch over async? Since we control the API, we should fix this to be async all the way.

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
> +                if (await ProcessEvent(eventName, messageData))
```suggestion
                if (await ProcessEventAsync(eventName, messageData))
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
> +    private async Task<bool> ProcessEvent(string eventName, string message)
```suggestion
    private async Task<bool> ProcessEventAsync(string eventName, string message)
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
> +    private Task ExceptionReceivedHandler(ExceptionReceivedEventArgs exceptionReceivedEventArgs)
```suggestion
    private Task ExceptionReceivedHandlerAsync(ExceptionReceivedEventArgs exceptionReceivedEventArgs)
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
> +            new MessageHandlerOptions(ExceptionReceivedHandler) { MaxConcurrentCalls = 10, AutoComplete = false });
```suggestion
            new MessageHandlerOptions(ExceptionReceivedHandlerAsync) { MaxConcurrentCalls = 10, AutoComplete = false });
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/EventBusServiceBus/EventBusServiceBus.cs
> +                .GetResult();
```suggestion
                .GetAwaiter()
                .GetResult();
```

This is a code smell.

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/IntegrationEventLogEF/Services/IntegrationEventLogService.cs
> +    private volatile bool disposedValue;
```suggestion
    private volatile bool _disposedValue;
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/IntegrationEventLogEF/Services/IntegrationEventLogService.cs
> +        if (!disposedValue)
```suggestion
        if (!_disposedValue)
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/IntegrationEventLogEF/Services/IntegrationEventLogService.cs
> +            disposedValue = true;
```suggestion
            _disposedValue = true;
```

2021-10-19 15:49 UTC, IEvangelist commented on src/BuildingBlocks/EventBus/IntegrationEventLogEF/Utilities/ResilientTransaction.cs
> +        new ResilientTransaction(context);
```suggestion
    public static ResilientTransaction New(DbContext context) => new(context);
```

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Basket/Basket.API/Infrastructure/Middlewares/FailingMiddleware.cs
> +using Microsoft.Extensions.Logging;
```suggestion

using Microsoft.Extensions.Logging;
```

Nit w/ new line

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Basket/Basket.FunctionalTests/Base/BasketTestStartup.cs
>  namespace Basket.FunctionalTests.Base
Why are we not doing the file-scaped namespace here?

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Basket/Basket.FunctionalTests/RedisBasketRepositoryTests.cs
> +﻿
Missing the file-scoped namespaces here too

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Identity/Identity.API/Devspaces/DevspacesRedirectUriValidator.cs
> +        private readonly ILogger _logger;
```suggestion
        private readonly ILogger _logger;

```

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.API/Application/Behaviors/LoggingBehavior.cs
> +﻿namespace Microsoft.eShopOnContainers.Services.Ordering.API.Application.Behaviors;
```suggestion
﻿namespace Microsoft.eShopOnContainers.Services.Ordering.API.Application.Behaviors;
﻿
```

I'm noticing that while we're now using file-scoped namespaces, that the namespace itself changed - why is that?

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.API/Application/DomainEventHandlers/BuyerAndPaymentMethodVerified/UpdateOrderWhenBuyerAndPaymentMethodVerifiedDomainEventHandler.cs
> +﻿namespace Microsoft.eShopOnContainers.Services.Ordering.API.Application.DomainEventHandlers.BuyerAndPaymentMethodVerified;
Again, here I'm not sure why the namespace is being changed? Sure, we're now doing file-scoped namespaces but this namespace went from:

`Ordering.API.Application.DomainEventHandlers.BuyerAndPaymentMethodVerified;`

To:

`Microsoft.eShopOnContainers.Services.Ordering.API.Application.DomainEventHandlers.BuyerAndPaymentMethodVerified;`

I prefer the original namespace

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.API/Application/Queries/OrderViewModel.cs
> +public record Order
These should be in separate files.

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.API/Startup.cs
> +namespace Microsoft.eShopOnContainers.Services.Ordering.API;
```suggestion
﻿namespace Microsoft.eShopOnContainers.Services.Ordering.API;
```

Nit

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.Domain/Events/OrderStartedDomainEvent.cs
> +namespace Microsoft.eShopOnContainers.Services.Ordering.Domain.Events
```suggestion﻿
namespace Microsoft.eShopOnContainers.Services.Ordering.Domain.Events
```

nit

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.Domain/Events/OrderStatusChangedToPaidDomainEvent.cs
> +public class OrderStatusChangedToPaidDomainEvent
```suggestion
﻿namespace Microsoft.eShopOnContainers.Services.Ordering.Domain.Events;
﻿  
/// <summary>
/// Event used when the order is paid
/// </summary>
public class OrderStatusChangedToPaidDomainEvent
```

nit

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.SignalrHub/IntegrationEvents/EventHandling/OrderStatusChangedToSubmittedIntegrationEventHandler.cs
> +    IIntegrationEventHandler<OrderStatusChangedToSubmittedIntegrationEvent>
```suggestion
﻿namespace Microsoft.eShopOnContainers.Services.Ordering.SignalrHub.IntegrationEvents.EventHandling;
﻿
public class OrderStatusChangedToSubmittedIntegrationEventHandler :
    IIntegrationEventHandler<OrderStatusChangedToSubmittedIntegrationEvent>
```

nit

2021-10-19 15:49 UTC, IEvangelist commented on src/Services/Ordering/Ordering.SignalrHub/IntegrationEvents/Events/OrderStatusChangedToAwaitingValidationIntegrationEvent.cs
> +public record OrderStatusChangedToAwaitingValidationIntegrationEvent : IntegrationEvent
```suggestion
﻿namespace Microsoft.eShopOnContainers.Services.Ordering.SignalrHub.IntegrationEvents;
﻿
public record OrderStatusChangedToAwaitingValidationIntegrationEvent : IntegrationEvent
```

2021-10-19 15:50 UTC, IEvangelist commented
Another question, why do we not have pull request build and test validation? We should certainly have that in place here. /cc @nishanil

2021-10-20 11:07 UTC, sughosneo commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/GrpcExceptionInterceptor.cs
> +            var response = await t;
ok

2021-10-20 11:08 UTC, sughosneo commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Models/BasketData.cs
> +    public List<BasketDataItem> Items { get; set; } = new List<BasketDataItem>();
Ok, sure

2021-10-20 11:09 UTC, sughosneo commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Services/OrderApiClient.cs
> +        var url = _urls.Orders + UrlsConfig.OrdersOperations.GetOrderDraft();
Yes, makes sense.

2021-10-20 11:32 UTC, sughosneo commented on src/BuildingBlocks/EventBus/EventBus/InMemoryEventBusSubscriptionsManager.cs
> +    public bool IsEmpty => !_handlers.Keys.Any();
Ok, sure

2021-10-20 11:37 UTC, sughosneo commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Services/IBasketService.cs
> +    Task<BasketData> GetById(string id);
Ok, sure.

2021-10-20 11:38 UTC, sughosneo commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Controllers/BasketController.cs
> +        var basket = await _basket.GetById(data.BuyerId) ?? new BasketData(data.BuyerId);
Yes, correct.

2021-10-20 11:39 UTC, sughosneo commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Infrastructure/HttpClientAuthorizationDelegatingHandler.cs
> +        if (!string.IsNullOrEmpty(authorizationHeader))
Right.

2021-10-20 11:40 UTC, sughosneo commented on src/ApiGateways/Web.Bff.Shopping/aggregator/Models/UpdateBasketItemData.cs
>      }
Good catch 👍

2021-10-20 11:50 UTC, sughosneo commented on src/Services/Basket/Basket.API/Infrastructure/Middlewares/FailingMiddleware.cs
> +using Microsoft.Extensions.Logging;
Right.

2021-10-20 11:58 UTC, sughosneo commented on src/Services/Ordering/Ordering.Domain/Events/OrderStartedDomainEvent.cs
> +namespace Microsoft.eShopOnContainers.Services.Ordering.Domain.Events
👍

2021-10-20 12:03 UTC, sughosneo commented on src/ApiGateways/Mobile.Bff.Shopping/aggregator/Filters/AuthorizeCheckOperationFilter.cs
>      namespace Basket.API.Infrastructure.Filters
Were getting this error message while building. 

![image](https://user-images.githubusercontent.com/13281246/138088823-e9c1c8cb-37ca-4a3d-bda8-9b36357544a0.png)

That's the reason I had kept it as block scoped namespace.

2021-10-20 12:07 UTC, sughosneo commented
> Another question, why do we not have pull request build and test validation? We should certainly have that in place here. /cc @nishanil

@IEvangelist  - This PR is directed to the `migration/net-6` branch. We have GitHub action enabled on those PR which are directed to the `dev` branch. Please refer :  https://github.com/dotnet-architecture/eShopOnContainers/blame/46219957ef763305030a0924d039fe4a25831b06/.github/workflows/basket-api.yml#L14

2021-10-20 13:23 UTC, IEvangelist approved these changes
Looks good to me, we'll :shipit: - thank you 🙏

2021-10-20 13:23 UTC, merged