Master
dotnet/eShopOnContainers pull request #348
Opened 2017-09-25 22:01 UTC by karumanchi1116

2017-11-08 22:31 UTC, jzeferino requested changes

2017-11-08 22:31 UTC, jzeferino commented on .env
> +#USE_LOADTEST=<True/False>
This was an unnecessary change to commit. nothing was changed.

2017-11-08 22:31 UTC, jzeferino commented on src/Mobile/README.md
> +eShopOnContainers is a reference app whose imagined purpose is to serve the mobile workforce of a fictitious company that sells products. The app would allow a user to manage their catalog, view prod
Suggestion:

> The app would **allows the user** to manage their catalog, view products, manage the basket/cart and the orders.

2017-11-08 22:31 UTC, jzeferino commented on src/Mobile/README.md
> -* a profile section with a order list
Suggestion:

> a profile section with a list of orders

2017-11-08 22:31 UTC, jzeferino commented on src/Mobile/README.md
> +In Windows 10, we press the start button and write MMC, short for Microsoft Management Console. Next, click the Hyper-V Manager option:
Suggestion:

> In Windows 10, ~~we~~ press the start button and write MMC, short for Microsoft Management Console. Next, click the Hyper-V Manager option:

2017-12-14 23:54 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=348) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=348) before we can accept your contribution.<br/><br/>:x: karumanchi1116 [sign now](https://cla.dotnetfoundation.org/dotnet-architecture/eShopOnContainers?pullRequest=348)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet-architecture/eShopOnContainers?pullRequest=348) it.</sub>

2018-03-26 16:23 UTC, mvelosop commented
Hi @karumanchi1116, thanks for your contributions, but we don't accept PRs to **master**, as per https://github.com/dotnet-architecture/eShopOnContainers/blob/master/branch-guide.md.

If you want to submit the PR, please fork the repo in GitHub and create the new branch from the current **dev**.

Please keep in mind that you must also sign the Contributor License Agreement (CLA) to accept th PR.

Thanks.

2018-03-26 16:23 UTC, closed without merging